# Generated by Django 4.2.24 on 2025-09-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(help_text='Nome único da categoria (ex.: Banho, Tosa, Hospedagem).', max_length=100, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nome',
            field=models.CharField(help_text='Nome do recurso ou estrutura (ex.: Canil, Consultório, Secador).', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='recursos',
            field=models.ManyToManyField(blank=True, help_text='Recursos necessários para este serviço.', related_name='servicos', to='contato.recurso', verbose_name='Recursos'),
        ),
    ]
